/* ============================================
   Dev Place - MAD MAN | Full Script
   ============================================ */

const APP = {
    page: '/',
    theme: localStorage.getItem('dp-theme') || 'dark',
    lang: localStorage.getItem('dp-lang') || 'ar',
    user: JSON.parse(localStorage.getItem('dp-user') || 'null'),
    users: JSON.parse(localStorage.getItem('dp-users') || '[]'),
    projects: JSON.parse(localStorage.getItem('dp-projects') || '[]'),
    deleteId: null,
};

// ============ ترجمة ============
const T = {
    ar: { home:'الرئيسية', about:'عن المطور', projects:'المشاريع', contact:'تواصل', dashboard:'لوحة التحكم', welcome:'مرحباً', tagline:'مبرمج محترف - صانع هوستات ومواقع', desc:'مبرمج محترف جداً، متخصص في صناعة الهوستات والمواقع الاحترافية. أقدم حلولاً تقنية متكاملة.', browse:'تصفح المشاريع', signup:'سوي حساب', stats1:'مشروع منجز', stats2:'عميل سعيد', stats3:'دعم فني', aboutMe:'عن المطور', name:'MAD MAN', aboutDesc1:'مبرمج محترف بخبرة واسعة في البرمجة وتطوير المواقع وصناعة الهوستات.', aboutDesc2:'متخصص في تصميم وتطوير المواقع الاحترافية وحلول الاستضافة المتكاملة.', projectsTitle:'المشاريع', projectsDesc:'مجموعة من المشاريع المجانية للجميع', contactTitle:'تواصل معي', contactDesc:'تقدر تتواصل معاي عبر هالقنوات', add:'إضافة مشروع', edit:'تعديل', save:'حفظ', cancel:'إلغاء', delete:'حذف', download:'تحميل', login:'دخول', logout:'خروج', email:'البريد', discord:'ديسكورد', telegram:'تلجرام', notSet:'لم يتم تحديد', profile:'الملف الشخصي', role:'المالك' },
    en: { home:'Home', about:'About', projects:'Projects', contact:'Contact', dashboard:'Dashboard', welcome:'Welcome', tagline:'Professional Developer - Host & Website Maker', desc:'Highly professional programmer specialized in hosting and websites.', browse:'Browse Projects', signup:'Create Account', stats1:'Projects Done', stats2:'Happy Clients', stats3:'24/7 Support', aboutMe:'About Me', name:'MAD MAN', aboutDesc1:'Professional programmer with extensive experience in web development and hosting.', aboutDesc2:'Specialized in professional website design and hosting solutions.', projectsTitle:'Projects', projectsDesc:'Free projects available for everyone', contactTitle:'Contact Me', contactDesc:'Reach me through these channels', add:'Add Project', edit:'Edit', save:'Save', cancel:'Cancel', delete:'Delete', download:'Download', login:'Login', logout:'Logout', email:'Email', discord:'Discord', telegram:'Telegram', notSet:'Not set', profile:'Profile', role:'Owner' }
};
function t(k){return T[APP.lang]?.[k]||T['ar'][k]||k}

// ============ تهيئة ============
(function init(){
    document.documentElement.setAttribute('data-theme',APP.theme);
    updateThemeIcon();
    if(APP.lang==='en'){document.documentElement.dir='ltr';document.querySelector('#langToggle span').textContent='AR';}
    if(!APP.users.length){APP.users.push({id:1,username:'Owner',email:'mohamedhere63@gmail.com',password:btoa('Owner123'),verified:true,role:'owner',discord:'81a0',telegram:'',created:new Date().toISOString()});saveUsers();}
    if(!APP.projects.length){APP.projects.push({id:1,title:'قالب موقع شخصي',desc:'قالب احترافي متجاوب مع جميع الأجهزة بتصميم عصري',type:'HTML/CSS/JS',status:'completed',file:'',downloads:120,created:new Date().toISOString()},{id:2,title:'لوحة تحكم هوست',desc:'لوحة تحكم بسيطة لإدارة ملفات الاستضافة',type:'PHP/MySQL',status:'completed',file:'',downloads:85,created:new Date().toISOString()},{id:3,title:'تطبيق مهام',desc:'تطبيق ويب لإدارة المهام اليومية',type:'React/Node.js',status:'in-progress',file:'',downloads:40,created:new Date().toISOString()},{id:4,title:'مكتبة أكواد جاهزة',desc:'مجموعة أكواد برمجية جاهزة للاستخدام',type:'JavaScript',status:'completed',file:'',downloads:200,created:new Date().toISOString()});saveProjects();}
    createParticles();
    router();
    updateAuthUI();
    window.addEventListener('scroll',handleScroll);
    document.addEventListener('click',handleGlobalClick);
    window.addEventListener('popstate',router);
    document.addEventListener('mousemove',handleMouseMove);
    document.getElementById('themeToggle').addEventListener('click',toggleTheme);
    document.getElementById('langToggle').addEventListener('click',toggleLang);
    document.getElementById('menuToggle').addEventListener('click',()=>document.getElementById('nav').classList.toggle('active'));
    document.getElementById('progressBar').style.width='0%';
})();

function saveUsers(){localStorage.setItem('dp-users',JSON.stringify(APP.users))}
function saveProjects(){localStorage.setItem('dp-projects',JSON.stringify(APP.projects))}

// ============ جسيمات ============
function createParticles(){
    const c=document.getElementById('particles');
    for(let i=0;i<30;i++){const p=document.createElement('div');p.className='particle';const s=2+Math.random()*4;p.style.width=s+'px';p.style.height=s+'px';p.style.left=Math.random()*100+'%';p.style.animationDuration=8+Math.random()*12+'s';p.style.animationDelay=Math.random()*10+'s';c.appendChild(p);}
}

// ============ مؤشر ============
function handleMouseMove(e){const c=document.querySelector('.cursor'),d=document.querySelector('.cursor-dot');if(c){c.style.left=e.clientX+'px';c.style.top=e.clientY+'px';d.style.left=e.clientX+'px';d.style.top=e.clientY+'px';}}

// ============ Router ============
function router(){
    APP.page=window.location.pathname;
    const a=document.getElementById('app');
    document.querySelectorAll('.nav-item').forEach(l=>{l.classList.remove('active');if(l.getAttribute('href')===APP.page)l.classList.add('active')});
    switch(APP.page){case'/':renderHome(a);break;case'/about':renderAbout(a);break;case'/projects':renderProjects(a);break;case'/contact':renderContact(a);break;case'/dashboard':renderDashboard(a);break;case'/register':renderRegister(a);break;case'/verify-email':renderVerify(a);break;case'/profile':renderProfile(a);break;default:render404(a);}
    window.scrollTo(0,0);
    document.getElementById('nav').classList.remove('active');
}
function navigateTo(p){history.pushState({},'',p);router()}
function handleGlobalClick(e){const l=e.target.closest('[data-link]');if(l){e.preventDefault();navigateTo(l.getAttribute('href'));}}

// ============ ثيم ============
function toggleTheme(){APP.theme=APP.theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',APP.theme);localStorage.setItem('dp-theme',APP.theme);updateThemeIcon()}
function toggleLang(){APP.lang=APP.lang==='ar'?'en':'ar';document.documentElement.dir=APP.lang==='ar'?'rtl':'ltr';document.querySelector('#langToggle span').textContent=APP.lang==='ar'?'EN':'AR';localStorage.setItem('dp-lang',APP.lang);router()}
function updateThemeIcon(){const i=document.querySelector('#themeToggle i');if(i)i.className=APP.theme==='dark'?'fas fa-sun':'fas fa-moon'}
function handleScroll(){const s=window.scrollY;document.getElementById('header').classList.toggle('scrolled',s>50);document.getElementById('progressBar').style.width=Math.min((s/(document.documentElement.scrollHeight-window.innerHeight))*100,100)+'%';if(s>60)document.getElementById('header').classList.add('scrolled')}

// ============ صفحات ============
function renderHome(a){a.innerHTML=`<section class="hero"><div class="hero-bg"><div class="hero-orb hero-orb-1"></div><div class="hero-orb hero-orb-2"></div><div class="hero-orb hero-orb-3"></div></div><div class="hero-content"><div class="hero-badge"><span class="dot"></span>${t('tagline')}</div><h1 class="hero-title"><span class="gradient-text">MAD MAN</span></h1><p class="hero-subtitle">${t('tagline')}</p><p class="hero-desc">${t('desc')}</p><div class="hero-buttons"><a href="/projects" class="btn-glow" data-link><i class="fas fa-code"></i> ${t('browse')}</a><a href="/register" class="btn-glass" data-link><i class="fas fa-user-plus"></i> ${t('signup')}</a></div><div class="hero-stats"><div class="stat-item"><div class="stat-number">+50</div><div class="stat-label">${t('stats1')}</div></div><div class="stat-item"><div class="stat-number">+30</div><div class="stat-label">${t('stats2')}</div></div><div class="stat-item"><div class="stat-number">24/7</div><div class="stat-label">${t('stats3')}</div></div></div></div></section>`}

function renderAbout(a){a.innerHTML=`<section style="padding:120px 0 80px"><div class="container"><div class="text-center mx-auto" style="margin-bottom:60px"><div class="section-label">👤 ${t('aboutMe')}</div><h2 class="section-title"><span>MAD MAN</span></h2><p class="section-sub">${t('aboutMe')}</p></div><div class="about-grid"><div class="about-visual"><div class="about-avatar-wrap"><div class="about-avatar-ring"></div><div class="about-avatar"><i class="fas fa-user-secret"></i></div><div class="about-floating-card"><i class="fas fa-circle" style="color:#10b981;"></i> متاح للعمل</div></div></div><div class="about-info"><h3>${t('name')}</h3><p>${t('aboutDesc1')}</p><p>${t('aboutDesc2')}</p><div class="info-cards"><div class="info-card"><div class="info-card-icon"><i class="fas fa-envelope"></i></div><div><h4>${t('email')}</h4><span>mohamedhere63@gmail.com <button class="copy-btn" onclick="copyText('mohamedhere63@gmail.com')"><i class="fas fa-copy"></i></button></span></div></div><div class="info-card"><div class="info-card-icon"><i class="fab fa-discord"></i></div><div><h4>${t('discord')}</h4><span>81a0 <button class="copy-btn" onclick="copyText('81a0')"><i class="fas fa-copy"></i></button></span></div></div><div class="info-card"><div class="info-card-icon"><i class="fab fa-telegram"></i></div><div><h4>${t('telegram')}</h4><span>${t('notSet')}</span></div></div></div><div class="skills-wrap"><span class="skill-tag">HTML5</span><span class="skill-tag">CSS3</span><span class="skill-tag">JavaScript</span><span class="skill-tag">Node.js</span><span class="skill-tag">PHP</span><span class="skill-tag">MySQL</span><span class="skill-tag">React</span><span class="skill-tag">Python</span></div></div></div></div></section>`}

function renderProjects(a){const o=APP.user?.role==='owner'||APP.user?.username==='Owner';let c=APP.projects.map(p=>`<div class="project-card"><div class="project-card-icon"><i class="fas fa-code"></i></div><h3>${p.title}</h3><p>${p.desc}</p><div class="project-meta"><span><i class="fas fa-download"></i> ${p.downloads||0}</span><span class="badge-sm ${p.status==='completed'?'badge-done':'badge-progress'}">${p.status==='completed'?'مكتمل':'قيد التطوير'}</span></div><div class="project-tags">${p.type.split('/').map(t=>`<span>${t.trim()}</span>`).join('')}</div><div class="project-actions"><button class="btn-sm-glass" onclick="downloadProject(${p.id})"><i class="fas fa-download"></i> ${t('download')}</button>${o?`<button class="btn-sm-glass" onclick="openProjectModal(${p.id})"><i class="fas fa-edit"></i></button><button class="btn-sm-glass danger" onclick="confirmDeleteProject(${p.id})"><i class="fas fa-trash"></i></button>`:''}</div></div>`).join('');a.innerHTML=`<section style="padding:120px 0 80px"><div class="container"><div class="text-center mx-auto" style="margin-bottom:60px"><div class="section-label">💻 ${t('projects')}</div><h2 class="section-title">${t('projectsTitle')}</h2><p class="section-sub">${t('projectsDesc')}</p></div>${o?`<div class="text-center" style="margin-bottom:30px"><button class="btn-glow" onclick="openProjectModal()"><i class="fas fa-plus"></i> ${t('add')}</button></div>`:''}<div class="projects-grid">${c||`<div class="empty-state"><i class="fas fa-folder-open"></i><p>لا توجد مشاريع</p></div>`}</div></div></section>`}

function renderContact(a){a.innerHTML=`<section style="padding:120px 0 80px"><div class="container"><div class="text-center mx-auto" style="margin-bottom:60px"><div class="section-label">📬 ${t('contact')}</div><h2 class="section-title">${t('contactTitle')}</h2><p class="section-sub">${t('contactDesc')}</p></div><div class="contact-grid"><div class="contact-card"><div class="contact-card-icon"><i class="fas fa-envelope"></i></div><h3>${t('email')}</h3><p>mohamedhere63@gmail.com</p><button class="copy-btn" onclick="copyText('mohamedhere63@gmail.com')"><i class="fas fa-copy"></i> نسخ</button></div><div class="contact-card"><div class="contact-card-icon"><i class="fab fa-discord"></i></div><h3>${t('discord')}</h3><p>81a0</p><button class="copy-btn" onclick="copyText('81a0')"><i class="fas fa-copy"></i> نسخ</button></div><div class="contact-card"><div class="contact-card-icon"><i class="fab fa-telegram"></i></div><h3>${t('telegram')}</h3><p>${t('notSet')}</p></div></div></div></section>`}

function renderDashboard(a){if(!APP.user){navigateTo('/');showToast('سجل دخولك أول','error');return}const to=APP.projects.length,dn=APP.projects.filter(p=>p.status==='completed').length,dl=APP.projects.reduce((s,p)=>s+(p.downloads||0),0),u=APP.users.find(u=>u.username===APP.user.username)||APP.user;a.innerHTML=`<div class="dashboard-layout"><aside class="dashboard-sidebar"><div class="sidebar-header"><div class="sidebar-logo">Dev <span>Place</span></div></div><nav class="sidebar-nav"><a href="/dashboard" class="active"><i class="fas fa-grid"></i> نظرة عامة</a><a href="/projects" data-link><i class="fas fa-folder"></i> المشاريع</a><a href="/profile" data-link><i class="fas fa-user"></i> الملف الشخصي</a></nav></aside><main class="dashboard-main"><div class="welcome-card"><div><h2>👋 ${t('welcome')} ${APP.user.username}!</h2><p style="opacity:0.85;">آخر دخول: اليوم</p></div><a href="/projects" class="btn-glass" data-link style="color:#fff;border-color:rgba(255,255,255,0.4);">إدارة المشاريع</a></div><div class="stats-grid"><div class="stat-card-db"><div class="stat-icon-db purple"><i class="fas fa-code"></i></div><div class="stat-info-db"><h3>${to}</h3><p>مشروع</p></div></div><div class="stat-card-db"><div class="stat-icon-db green"><i class="fas fa-check"></i></div><div class="stat-info-db"><h3>${dn}</h3><p>مكتمل</p></div></div><div class="stat-card-db"><div class="stat-icon-db blue"><i class="fas fa-download"></i></div><div class="stat-info-db"><h3>${dl}</h3><p>تحميل</p></div></div><div class="stat-card-db"><div class="stat-icon-db pink"><i class="fas fa-star"></i></div><div class="stat-info-db"><h3>4.9</h3><p>تقييم</p></div></div></div><div class="info-grid"><div class="info-block"><div class="info-block-header">👤 معلومات الحساب</div><div class="info-block-body"><div class="info-row"><div class="info-row-icon"><i class="fas fa-user"></i></div><div><strong>الاسم</strong><span>${u.username}</span></div></div><div class="info-row"><div class="info-row-icon"><i class="fas fa-envelope"></i></div><div><strong>${t('email')}</strong><span>${u.email} <button class="copy-btn" onclick="copyText('${u.email}')"><i class="fas fa-copy"></i></button></span></div></div><div class="info-row"><div class="info-row-icon"><i class="fab fa-discord"></i></div><div><strong>${t('discord')}</strong><span>${u.discord||'81a0'}</span></div></div><div class="info-row"><div class="info-row-icon"><i class="fab fa-telegram"></i></div><div><strong>${t('telegram')}</strong><span>${u.telegram||t('notSet')}</span></div></div></div></div></div></main></div>`}

function renderRegister(a){if(APP.user){navigateTo('/dashboard');return}a.innerHTML=`<section class="auth-page"><div class="auth-card"><div class="auth-card-header"><div class="auth-logo">Dev Place</div><p>انضم إلينا</p></div><div class="auth-card-body"><form onsubmit="handleRegister(event)"><div class="input-group"><i class="fas fa-user"></i><input type="text" id="regUser" placeholder="اسم المستخدم" required></div><div class="input-group"><i class="fas fa-envelope"></i><input type="email" id="regEmail" placeholder="البريد الإلكتروني" required></div><div class="input-row"><div class="input-group"><i class="fab fa-discord"></i><input type="text" id="regDiscord" placeholder="ديسكورد"></div><div class="input-group"><i class="fab fa-telegram"></i><input type="text" id="regTelegram" placeholder="تلجرام"></div></div><div class="input-group"><i class="fas fa-key"></i><input type="password" id="regPass" placeholder="كلمة المرور" required minlength="6"><button type="button" class="toggle-pass-btn" onclick="togglePassword('regPass',this)"><i class="fas fa-eye"></i></button></div><div class="form-error" id="regError"></div><div class="form-success" id="regSuccess"></div><button type="submit" class="btn-glow btn-full"><span>إنشاء حساب</span><i class="fas fa-arrow-left"></i></button></form><p class="modal-footer-text">عندك حساب؟ <a href="/" onclick="openModal('loginModal');return false;">دخول</a></p></div></div></section>`}

function renderVerify(a){const p=new URLSearchParams(window.location.search),token=p.get('token'),email=p.get('email');let h='';if(token&&email){const u=APP.users.find(u=>u.email===email&&u.verificationToken===token);if(u){u.verified=true;u.verificationToken=null;saveUsers();h=`<section class="auth-page"><div class="auth-card"><div class="auth-card-header"><div class="auth-logo">✅</div><p>تم التفعيل</p></div><div class="auth-card-body text-center"><p style="font-size:3rem;">✅</p><p>بريدك مفعل</p><a href="/" class="btn-glow" style="margin-top:16px;" onclick="openModal('loginModal');return false;">سجل دخولك</a></div></div></section>`}else h=`<section class="auth-page"><div class="auth-card"><div class="auth-card-header"><div class="auth-logo">❌</div><p>خطأ</p></div><div class="auth-card-body text-center"><p>الرابط غير صالح</p></div></div></section>`}else h=`<section class="auth-page"><div class="auth-card"><div class="auth-card-header"><div class="auth-logo">❌</div><p>خطأ</p></div><div class="auth-card-body text-center"><p>رابط غير صالح</p></div></div></section>`;a.innerHTML=h}

function renderProfile(a){if(!APP.user){navigateTo('/');return}const u=APP.users.find(u=>u.username===APP.user.username)||APP.user;a.innerHTML=`<section class="profile-page"><div class="profile-card"><div class="profile-cover"></div><div class="profile-avatar-lg"><i class="fas fa-user-secret"></i></div><div class="profile-body"><h2>${u.username}</h2><div class="role-badge">${u.role==='owner'?t('role'):'مستخدم'}</div><div class="profile-details"><div class="pd-row"><div class="pd-icon"><i class="fas fa-envelope"></i></div><div class="pd-info"><strong>${t('email')}</strong><span>${u.email} <button class="copy-btn" onclick="copyText('${u.email}')"><i class="fas fa-copy"></i></button></span></div></div><div class="pd-row"><div class="pd-icon"><i class="fab fa-discord"></i></div><div class="pd-info"><strong>${t('discord')}</strong><span>${u.discord||'81a0'}</span></div></div><div class="pd-row"><div class="pd-icon"><i class="fab fa-telegram"></i></div><div class="pd-info"><strong>${t('telegram')}</strong><span>${u.telegram||t('notSet')}</span></div></div></div></div></div></section>`}

function render404(a){a.innerHTML=`<section class="error-section"><div><div class="error-code">404</div><p>الصفحة غير موجودة</p><a href="/" class="btn-glow" data-link><i class="fas fa-home"></i> الرئيسية</a></div></section>`}

// ============ Auth ============
function handleLogin(e){e.preventDefault();const u=document.getElementById('loginUser').value.trim(),p=document.getElementById('loginPass').value.trim(),er=document.getElementById('loginError');const user=APP.users.find(x=>x.username===u||x.email===u);if(!user||atob(user.password)!==p){er.textContent='غلط في الاسم أو كلمة المرور';return}APP.user={id:user.id,username:user.username,email:user.email,role:user.role,verified:user.verified,discord:user.discord,telegram:user.telegram};localStorage.setItem('dp-user',JSON.stringify(APP.user));closeModal('loginModal');updateAuthUI();navigateTo('/dashboard');showToast(`👋 ${t('welcome')} ${user.username}!`,'success')}

function handleRegister(e){e.preventDefault();const u=document.getElementById('regUser').value.trim(),em=document.getElementById('regEmail').value.trim(),d=document.getElementById('regDiscord').value.trim(),tg=document.getElementById('regTelegram').value.trim(),p=document.getElementById('regPass').value.trim(),er=document.getElementById('regError'),sc=document.getElementById('regSuccess');er.textContent='';sc.style.display='none';if(p.length<6){er.textContent='كلمة المرور 6 أحرف على الأقل';return}if(APP.users.find(x=>x.username===u)){er.textContent='اسم المستخدم مستخدم';return}if(APP.users.find(x=>x.email===em)){er.textContent='البريد مستخدم';return}const token='v_'+Math.random().toString(36).substr(2,9);APP.users.push({id:APP.users.length+1,username:u,email:em,password:btoa(p),verified:false,verificationToken:token,role:'user',discord:d,telegram:tg,created:new Date().toISOString()});saveUsers();sc.textContent='✅ تم! شيك بريدك';sc.style.display='block';e.target.reset();console.log(`📧 Verify: /verify-email?token=${token}&email=${em}`);setTimeout(()=>navigateTo(`/verify-email?token=${token}&email=${em}`),2000)}

function logout(){APP.user=null;localStorage.removeItem('dp-user');updateAuthUI();navigateTo('/');showToast('تم الخروج')}

// ============ مشاريع ============
function openProjectModal(id=null){document.getElementById('projectId').value=id||'';document.getElementById('projectModalTitle').textContent=id?t('edit')+' مشروع':t('add');document.getElementById('projectSubmitBtn').innerHTML=`<span>${t('save')}</span><i class="fas fa-save"></i>`;if(id){const p=APP.projects.find(x=>x.id===id);if(p){document.getElementById('projectTitle').value=p.title;document.getElementById('projectDesc').value=p.desc;document.getElementById('projectType').value=p.type;document.getElementById('projectStatus').value=p.status;document.getElementById('projectFile').value=p.file||''}}else{document.getElementById('projectTitle').value='';document.getElementById('projectDesc').value='';document.getElementById('projectType').value='';document.getElementById('projectStatus').value='completed';document.getElementById('projectFile').value=''}document.getElementById('projectError').textContent='';openModal('projectModal')}
function saveProject(e){e.preventDefault();const id=parseInt(document.getElementById('projectId').value)||null,ti=document.getElementById('projectTitle').value.trim(),de=document.getElementById('projectDesc').value.trim(),ty=document.getElementById('projectType').value.trim(),st=document.getElementById('projectStatus').value,fi=document.getElementById('projectFile').value.trim(),er=document.getElementById('projectError');if(!ti||!de||!ty){er.textContent='كل الحقول مطلوبة';return}if(id){const p=APP.projects.find(x=>x.id===id);if(p){p.title=ti;p.desc=de;p.type=ty;p.status=st;p.file=fi}}else APP.projects.push({id:Date.now(),title:ti,desc:de,type:ty,status:st,file:fi,downloads:0,created:new Date().toISOString()});saveProjects();closeModal('projectModal');router();showToast('✅ تم الحفظ','success')}
function confirmDeleteProject(id){APP.deleteId=id;document.getElementById('confirmDeleteBtn').onclick=()=>{deleteProject(APP.deleteId);closeModal('deleteModal')};openModal('deleteModal')}
function deleteProject(id){APP.projects=APP.projects.filter(x=>x.id!==id);saveProjects();router();showToast('🗑️ تم الحذف')}
function downloadProject(id){const p=APP.projects.find(x=>x.id===id);if(p){p.downloads=(p.downloads||0)+1;saveProjects();showToast(`📥 ${p.title}`,'success');if(p.file)window.open(p.file,'_blank')}}

// ============ مودال ============
function openModal(id){document.getElementById(id).classList.add('active');document.body.style.overflow='hidden'}
function closeModal(id){document.getElementById(id).classList.remove('active');document.body.style.overflow='';if(id==='loginModal'){document.getElementById('loginForm').reset();document.getElementById('loginError').textContent=''}}

// ============ UI ============
function updateAuthUI(){const lb=document.getElementById('loginBtnHeader'),um=document.getElementById('userMenu');if(APP.user){lb.style.display='none';um.style.display='block';document.getElementById('userMenuName').textContent=APP.user.username}else{lb.style.display='flex';um.style.display='none'}}
function copyText(tx){navigator.clipboard.writeText(tx).then(()=>showToast('✅ نسخ!','success'))}
function togglePassword(id,btn){const i=document.getElementById(id),ic=btn.querySelector('i');i.type=i.type==='password'?'text':'password';ic.className=i.type==='password'?'fas fa-eye':'fas fa-eye-slash'}
function showToast(msg,type=''){const c=document.getElementById('toasts');const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=msg;c.appendChild(t);setTimeout(()=>t.remove(),3000)}
